In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/energy_data.csv")
df.head()

             timestamp  fridge    ac  lights  microwave  total_power
0  2023-01-01 00:00:00      85     0      36          0          121
1  2023-01-01 01:00:00       0     0      73       1023         1096
2  2023-01-01 02:00:00       0     0      43          0           43
3  2023-01-01 03:00:00     167     0      22        840         1029
4  2023-01-01 04:00:00     116  1881      50          0         2047

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4321 entries, 0 to 4320
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    4321 non-null   str
 1   fridge       4321 non-null   int64
 2   ac           4321 non-null   int64
 3   lights       4321 non-null   int64
 4   microwave    4321 non-null   int64
 5   total_power  4321 non-null   int64
dtypes: int64(5), str(1)
memory usage: 202.7 KB

In [5]:
df.isnull().sum()

timestamp      0
fridge         0
ac             0
lights         0
microwave      0
total_power    0
dtype: int64

In [6]:
df.describe()

            fridge           ac       lights    microwave  total_power
count  4321.000000  4321.000000  4321.000000  4321.000000  4321.000000
mean     85.193474   778.190465    32.175422    95.936589   991.495950
std      67.725710   916.295285    34.410267   296.255725   959.856719
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000   119.000000
50%      90.000000     0.000000    25.000000     0.000000   830.000000
75%     145.000000  1666.000000    63.000000     0.000000  1849.000000
max     199.000000  2498.000000    99.000000  1199.000000  3798.000000

In [11]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.head()

            timestamp  fridge    ac  lights  microwave  total_power
0 2023-01-01 00:00:00      85     0      36          0          121
1 2023-01-01 01:00:00       0     0      73       1023         1096
2 2023-01-01 02:00:00       0     0      43          0           43
3 2023-01-01 03:00:00     167     0      22        840         1029
4 2023-01-01 04:00:00     116  1881      50          0         2047

In [13]:
import matplotlib.pyplot as plt

df['total_power'].plot(figsize=(10,4))
plt.title("Total Energy Consumption Over Time")
plt.xlabel("Time")
plt.ylabel("Power (Watts)")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'